# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - FOLDERNAME='eispy'
        - PYTHON_VERSION=3.7
        - CONDA_DEPENDENCIES='astropy sphinx graphviz'
        - PIP_DEPENDENCIES='cookiecutter gitpython pytest-astropy sphinx-astropy sunpy_sphinx_theme sunpy[net]'
        - EVENT_TYPE='pull_request push'
        - TASK='test'
        - EXTRA_CONTEXT=''
        - FLAGS=''

    matrix:
      # Extra context is a way to override options that the user normally
      # specifies during the questions phase of the cookiecutter setup. The keys
      # being overridden here must exist in the cookiecutter.json
      # See https://cookiecutter.readthedocs.io/en/0.9.1/advanced_usage.html#injecting-extra-context
      - EXTRA_CONTEXT=''

install:

    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

jobs:
  include:
    - name: "Unit tests"
      script:
         - python -m pip install pytest-cov
         - python setup.py egg_info
         - python setup.py build
         - python setup.py test
    - name: "Build docs"
      script:
        - python setup.py install
        - cd docs
        - make html




after_success:
  - python -m pip install codecov
  - codecov
